### ISSUE TITLE
(Spec) Top segment is off-spec

### ISSUE THREAD

**Issue by CharlesDLandau** [MarianiVentura/prj-rev-bwfs-dasmoto#1]
When I tested your page, I noticed that the top segment was off spec. See the comparison below

![image](https://user-images.githubusercontent.com/27013838/40590192-ac1081a8-61c8-11e8-9c35-813ce37333f7.png)
![image](https://user-images.githubusercontent.com/27013838/40590195-b0fcd57c-61c8-11e8-808f-88fae832e70e.png)

**Comment by MarianiVentura** [comment]
Charles,

Thank you.  Yes, I knew the background image was not showing, but I couldn't figure out what I was doing wrong.  Additionally, I don't know how to view your source compared to mine to see what I did wrong...?
Michael

**Comment by CharlesDLandau** [comment]
I used the solution set, which I believe is available on the project landing page. In the solution, the CSS loads the background image from AWS and points to the HEAD tag.
